/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author bouvr
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        cadre = BorderFactory.createLineBorder(Color.orange);
        saisieDialog = new Saisie(this, true);
        InitContacts();
        
        //jScrollPane1.setHorizontalScrollBar(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BoiteGlobale = new javax.swing.JPanel();
        jBoiteScroll = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBoiteContacts = new javax.swing.JPanel();
        jBoiteInfos = new javax.swing.JPanel();
        btnPlus = new javax.swing.JButton();
        btnMoins = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jQuit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BoiteGlobale.setBackground(new java.awt.Color(0, 150, 150));
        BoiteGlobale.setLayout(new java.awt.GridLayout(1, 0));

        jBoiteScroll.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des contacts"));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(430, 100));

        jBoiteContacts.setPreferredSize(new java.awt.Dimension(330, 353));

        javax.swing.GroupLayout jBoiteContactsLayout = new javax.swing.GroupLayout(jBoiteContacts);
        jBoiteContacts.setLayout(jBoiteContactsLayout);
        jBoiteContactsLayout.setHorizontalGroup(
            jBoiteContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        jBoiteContactsLayout.setVerticalGroup(
            jBoiteContactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jBoiteContacts);

        javax.swing.GroupLayout jBoiteScrollLayout = new javax.swing.GroupLayout(jBoiteScroll);
        jBoiteScroll.setLayout(jBoiteScrollLayout);
        jBoiteScrollLayout.setHorizontalGroup(
            jBoiteScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBoiteScrollLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jBoiteScrollLayout.setVerticalGroup(
            jBoiteScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBoiteScrollLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jBoiteInfos.setBorder(javax.swing.BorderFactory.createTitledBorder("Infos ?"));
        jBoiteInfos.setPreferredSize(new java.awt.Dimension(360, 353));

        javax.swing.GroupLayout jBoiteInfosLayout = new javax.swing.GroupLayout(jBoiteInfos);
        jBoiteInfos.setLayout(jBoiteInfosLayout);
        jBoiteInfosLayout.setHorizontalGroup(
            jBoiteInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jBoiteInfosLayout.setVerticalGroup(
            jBoiteInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnMoins.setText("-");
        btnMoins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoinsActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jQuit.setText("Quit");
        jQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuitActionPerformed(evt);
            }
        });
        jMenu1.add(jQuit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jHelp.setText("About");
        jHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHelpActionPerformed(evt);
            }
        });
        jMenu2.add(jHelp);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BoiteGlobale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPlus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMoins))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBoiteScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jBoiteInfos, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBoiteScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoiteInfos, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(BoiteGlobale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPlus)
                            .addComponent(btnMoins))))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jQuitActionPerformed

    private void jHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHelpActionPerformed
        // TODO add your handling code here:
        
        About about1 = new About(this, true);
        about1.setLocationRelativeTo(this);
        about1.setPhoto("Photos/about.png");
        about1.setVisible(true);
    }//GEN-LAST:event_jHelpActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        // TODO add your handling code here:
        
        saisieDialog.initDataChanged();
        saisieDialog.setLocationRelativeTo(this);
        saisieDialog.setPhoto("Photos/modifier.png");
        saisieDialog.setVisible(true);
       
        if (saisieDialog.getDataChanged() == true) {
            jBoiteContacts.removeAll();
            InitContacts();     
        }
        
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoinsActionPerformed
        // TODO add your handling code here:
        
        saisieDialog.SupprimeLeContact(num_Contact);
        jBoiteContacts.removeAll();
        InitContacts();
    }//GEN-LAST:event_btnMoinsActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private void InitContacts() {
        
        String [][] ListePersonnes = {  {"Peter","Pan","Photos/carte0.png"}, {"Tom","Sawyer","Photos/carte1.png"},        
            {"Peter","Gabriel", "Photos/carte2.png"}, {"Edith","Piaf", "Photos/carte3.png"}   };
        
        int nbPersonne;
        
        //ListeContacts = new Contact[ListePersonnes.length];
        ListeContacts = new Contact[50];
        
        Dimension taille = (new Contact(ListePersonnes[0], 0)).getPreferredSize();
        String Chaine;
        String [] Infos;
        int i = 0;
        /*        
        for (int i = 0 ; i < ListePersonnes.length ; i++) {
            ListeContacts[i] = new Contact(ListePersonnes[i], i);  
            ListeContacts[i].setBounds(0, (taille.height+2) * i, taille.width, taille.height);
            jBoiteContacts.add(ListeContacts[i]);         
        }
        */
        Fichier Fic = new Fichier();
        Fic.OpenReadByLine("Donnees/listeContacts.txt");     //ListePersonnes
        System.out.println("Boucle InitContacts");
        do {
            Chaine = Fic.Lire();
            //System.out.println(Chaine);
            if (Chaine != null) {
                Infos = Fic.ExtractData(Chaine);
                ListeContacts[i] = new Contact(Infos, i);   
                ListeContacts[i].setBounds(0, (taille.height+2) * i, taille.width, taille.height);
                
                ListeContacts[i].addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseReleased(java.awt.event.MouseEvent evt) {
                        // exécuter la méthode :
                        contactMouseReleased(evt);
                        }
                    });

                
                jBoiteContacts.add(ListeContacts[i]);  
                i++;
            }
            
        } while (Chaine != null);
        
        nbPersonne = i;
        //taille.setSize(taille.width, (taille.height+2) * ListePersonnes.length );
        taille.setSize(taille.width, (taille.height+2) * nbPersonne );
        jBoiteContacts.setPreferredSize(taille);
        jBoiteContacts.validate();
        
        num_Contact = 0;
        PrevNumContact = 0;
        ListeContacts[0].setBorder(cadre);
        
        infos1 = new Infos(ListeContacts[0].getListeInfos());
        taille = infos1.getPreferredSize();                                     //Pourquoi ?
        infos1.setBounds(10, 20, taille.width, taille.height);                  //Pourquoi ?
        jBoiteInfos.add(infos1);
        jBoiteInfos.validate();
    }    
    
    private void contactMouseReleased(java.awt.event.MouseEvent evt) {
        Contact contactClique = (Contact) evt.getSource();
        num_Contact = contactClique.getId();
        ListeContacts[PrevNumContact].setBorder(null);
        ListeContacts[num_Contact].setBorder(cadre);
        infos1.setInfos(ListeContacts[num_Contact].getListeInfos());
        PrevNumContact = num_Contact;
    }
    private Infos infos1;
    private Contact ListeContacts[];
    private Border cadre;
    private int PrevNumContact = 0;
    private int num_Contact = 0;
    private Saisie saisieDialog;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoiteGlobale;
    private javax.swing.JButton btnMoins;
    private javax.swing.JButton btnPlus;
    private javax.swing.JPanel jBoiteContacts;
    private javax.swing.JPanel jBoiteInfos;
    private javax.swing.JPanel jBoiteScroll;
    private javax.swing.JMenuItem jHelp;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jQuit;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
